version: "3.3"
services:
  db:
    restart: always
    image: postgres:12.3
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_DB: dtu_test_project
      POSTGRES_PASSWORD: root
      POSTGRES_USER: postgres
    expose:
      - "5432"
    volumes:
      - "dtu_test_db_data:/var/lib/postgresql/data"
    ports:
      - "5432:5432"

volumes:
  dtu_test_db_data:
    external: true
